---
openapi: 3.0.0
info:
  title: Nava API
  description: This is the api document for nava application
  contact:
    email: nava@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/HOSAINPISHGAHI/Nava/1.0.0
  description: SwaggerHub API Auto Mocking
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
paths:
  /PlayList/{id}:
    get:
      summary: get playlist by id
      description: |
        By passing in the id of a playlist of user, you can retrieve it
        which contains a list of music for you in the playlist
      operationId: retrievePlaylist
      parameters:
      - name: id
        in: path
        description: ID of the palylist to retrieve
        required: true
        style: simple
        explode: false
        schema:
          type: integer
      responses:
        "200":
          description: search results matching criteria
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Music'
        "400":
          description: bad input parameter
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        username:
          type: string
          example: ali alavi
        email:
          type: string
          example: example@gmail.com
        accountType:
          type: string
          example: listener
    Music:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
          example: hello
        artist:
          type: string
          example: adele
        duration:
          type: string
          example: "210"
        description:
          type: string
          example: a single music by adele
    Comment:
      type: object
      properties:
        text:
          type: string
          example: such a good music
        dateAndTime:
          type: string
          format: date-time
          example: 2016-08-29T09:12:33.001Z
        user:
          $ref: '#/components/schemas/User'
        Music:
          $ref: '#/components/schemas/Music'
